version: '3'

services:
  mariadb_ss:
    container_name: db_of_maria
    image: mariadb:10.7.3-focal
    ports: 
      - 33060:33060
      - 3306:3306
    env_file:
      - ./mariadb.env  
    volumes: 
      - ./mariadb_dir:/var/lib/mysql

  signserver-service:
    container_name: signserver_kemenlu_demo_mariadb
    image: primekey/signserver-ce:5.2.0
    ports:
      - 8443:8443
      - 443:8443
      - 8080:8080
    environment:
      - DATABASE_JDBC_URL=jdbc:mysql://db_of_maria:3306/signserverdb?characterEncoding=UTF-8
    env_file:
      - ./mariadb.env
    hostname: ss.kemenlu_demo.id
    volumes:
      - ./certa/keystore.jks:/mnt/persistent/secrets/tls/ss.kemenlu_demo.id/server.jks:ro
      - ./certa/keystore.storepasswd:/mnt/persistent/secrets/tls/ss.kemenlu_demo.id/server.storepasswd:ro
      - ./certa_pem/certificate.pem:/mnt/external/secrets/tls/cas/ManagementCA1.crt:ro
    depends_on: 
      - mariadb_ss
