version: '3'

services:
  signserver-service:
    container_name: signserver
    image: primekey/signserver-ce:5.2.0
    ports:
      - 8443:8443
      - 443:8443
      - 8080:8080
    hostname: ss.gehirn.org
    volumes:
      - ../dckr_vols:/mnt/uyo
      - ../certa/keystore.jks:/mnt/persistent/secrets/tls/ss.gehirn.org/server.jks:ro
      - ../certa/keystore.storepasswd:/mnt/persistent/secrets/tls/ss.gehirn.org/server.storepasswd:ro
      - ../certa_pem/certificate.pem:/mnt/external/secrets/tls/cas/ManagementCA1.crt:ro