FROM centos:centos8.3.2011
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN dnf --assumeyes install openssl java-1.8.0-openjdk-headless
RUN dnf --assumeyes install diffutils.x86_64 ncurses-devel